# Generated by Django 5.1.15 on 2026-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_adminupi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="game_mode",
            field=models.CharField(
                choices=[
                    ("BR_SOLO", "Battle Royale — Solo"),
                    ("BR_DUO", "Battle Royale — Duo"),
                    ("BR_SQUAD", "Battle Royale — Squad"),
                    ("CS_SOLO", "Clash Squad — Solo"),
                    ("CS_DUO", "Clash Squad — Duo"),
                    ("CS_SQUAD", "Clash Squad — Squad"),
                    ("LW_1V1", "Lone Wolf 1v1"),
                    ("LW_2V2", "Lone Wolf 2v2"),
                ],
                max_length=20,
            ),
        ),
    ]
